vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        museums:
            uri_prefix: /images/museums
            upload_destination: '%kernel.project_dir%/public/images/museums'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
